#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.tempo.storage.backend.secret.name != "":
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: #@ data.values.tempo.storage.backend.secret.name
  namespace: #@ data.values.tempo.storage.backend.secret.namespace
spec:
  toNamespaces:
    - #@ data.values.tempo.namespace

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: #@ data.values.tempo.storage.backend.secret.name
  namespace: #@ data.values.tempo.namespace
spec:
  fromNamespace: #@ data.values.tempo.storage.backend.secret.namespace
#@ end
